### ISSUE TITLE
Does it support AD?

### ISSUE THREAD

**Issue by wemeya** [hamano/golang-openldap#2]
@hamano 
hi, we use ldap in our project, when using ldap, it works fine.
However, when switch to AD, it complains an error:  LDAP::Bind() error (49) : Invalid credentials
Do you know the reason?
Thanks!

**Comment by hamano** [comment]
Yes, This is just libldap(OpenLDAP) wrapper, so no reason don't work with AD.
First, I recommend you to try ldapsearch command.
Did you confirm around TLS certificate?
Thank you!
